/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum body_style_type {
  CONVERTIBLE, COUPE, HATCHBACK, MINIVAN, PICKUP, SUV, SEDAN, VAN, WAGON  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"body_style_type\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"CONVERTIBLE\",\"COUPE\",\"HATCHBACK\",\"MINIVAN\",\"PICKUP\",\"SUV\",\"SEDAN\",\"VAN\",\"WAGON\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
