/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype {
  CONTACT_FORM, ALTERNATIVE, CONTACT_BUTTON, FEATURES, GET_DIRECTIONS, VEHICLE_HISTORY, BADGE_DETAIL, PHOTO_MODAL, BADGES, MARKET_REPORT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"CONTACT_FORM\",\"ALTERNATIVE\",\"CONTACT_BUTTON\",\"FEATURES\",\"GET_DIRECTIONS\",\"VEHICLE_HISTORY\",\"BADGE_DETAIL\",\"PHOTO_MODAL\",\"BADGES\",\"MARKET_REPORT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
