/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum vehicle_condition_types {
  NEW, USED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"vehicle_condition_types\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"NEW\",\"USED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
