/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BodyStyle {
  Chassis, Convertible, Coupe, Hatchback, Minivan, Pickup, SUV, Sedan, Van, Wagon  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BodyStyle\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"Chassis\",\"Convertible\",\"Coupe\",\"Hatchback\",\"Minivan\",\"Pickup\",\"SUV\",\"Sedan\",\"Van\",\"Wagon\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
