/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CabStyle {
  Regular, Extended, Crew  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CabStyle\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"Regular\",\"Extended\",\"Crew\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
