/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Condition {
  New, Used, CPO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Condition\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"New\",\"Used\",\"CPO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
