/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign8;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EventSubtypeStatisticsData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5783663187253058019L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventSubtypeStatisticsData\",\"namespace\":\"com.refactorlabs.cs378.assign8\",\"fields\":[{\"name\":\"session_count\",\"type\":\"long\",\"default\":1},{\"name\":\"total_count\",\"type\":\"long\",\"default\":1},{\"name\":\"sum_of_squares\",\"type\":\"long\",\"default\":1},{\"name\":\"mean\",\"type\":\"double\",\"default\":0.0},{\"name\":\"variance\",\"type\":\"double\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long session_count;
  @Deprecated public long total_count;
  @Deprecated public long sum_of_squares;
  @Deprecated public double mean;
  @Deprecated public double variance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventSubtypeStatisticsData() {}

  /**
   * All-args constructor.
   * @param session_count The new value for session_count
   * @param total_count The new value for total_count
   * @param sum_of_squares The new value for sum_of_squares
   * @param mean The new value for mean
   * @param variance The new value for variance
   */
  public EventSubtypeStatisticsData(java.lang.Long session_count, java.lang.Long total_count, java.lang.Long sum_of_squares, java.lang.Double mean, java.lang.Double variance) {
    this.session_count = session_count;
    this.total_count = total_count;
    this.sum_of_squares = sum_of_squares;
    this.mean = mean;
    this.variance = variance;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return session_count;
    case 1: return total_count;
    case 2: return sum_of_squares;
    case 3: return mean;
    case 4: return variance;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: session_count = (java.lang.Long)value$; break;
    case 1: total_count = (java.lang.Long)value$; break;
    case 2: sum_of_squares = (java.lang.Long)value$; break;
    case 3: mean = (java.lang.Double)value$; break;
    case 4: variance = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'session_count' field.
   * @return The value of the 'session_count' field.
   */
  public java.lang.Long getSessionCount() {
    return session_count;
  }

  /**
   * Sets the value of the 'session_count' field.
   * @param value the value to set.
   */
  public void setSessionCount(java.lang.Long value) {
    this.session_count = value;
  }

  /**
   * Gets the value of the 'total_count' field.
   * @return The value of the 'total_count' field.
   */
  public java.lang.Long getTotalCount() {
    return total_count;
  }

  /**
   * Sets the value of the 'total_count' field.
   * @param value the value to set.
   */
  public void setTotalCount(java.lang.Long value) {
    this.total_count = value;
  }

  /**
   * Gets the value of the 'sum_of_squares' field.
   * @return The value of the 'sum_of_squares' field.
   */
  public java.lang.Long getSumOfSquares() {
    return sum_of_squares;
  }

  /**
   * Sets the value of the 'sum_of_squares' field.
   * @param value the value to set.
   */
  public void setSumOfSquares(java.lang.Long value) {
    this.sum_of_squares = value;
  }

  /**
   * Gets the value of the 'mean' field.
   * @return The value of the 'mean' field.
   */
  public java.lang.Double getMean() {
    return mean;
  }

  /**
   * Sets the value of the 'mean' field.
   * @param value the value to set.
   */
  public void setMean(java.lang.Double value) {
    this.mean = value;
  }

  /**
   * Gets the value of the 'variance' field.
   * @return The value of the 'variance' field.
   */
  public java.lang.Double getVariance() {
    return variance;
  }

  /**
   * Sets the value of the 'variance' field.
   * @param value the value to set.
   */
  public void setVariance(java.lang.Double value) {
    this.variance = value;
  }

  /**
   * Creates a new EventSubtypeStatisticsData RecordBuilder.
   * @return A new EventSubtypeStatisticsData RecordBuilder
   */
  public static com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder newBuilder() {
    return new com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder();
  }

  /**
   * Creates a new EventSubtypeStatisticsData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventSubtypeStatisticsData RecordBuilder
   */
  public static com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder newBuilder(com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder other) {
    return new com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder(other);
  }

  /**
   * Creates a new EventSubtypeStatisticsData RecordBuilder by copying an existing EventSubtypeStatisticsData instance.
   * @param other The existing instance to copy.
   * @return A new EventSubtypeStatisticsData RecordBuilder
   */
  public static com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder newBuilder(com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData other) {
    return new com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder(other);
  }

  /**
   * RecordBuilder for EventSubtypeStatisticsData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventSubtypeStatisticsData>
    implements org.apache.avro.data.RecordBuilder<EventSubtypeStatisticsData> {

    private long session_count;
    private long total_count;
    private long sum_of_squares;
    private double mean;
    private double variance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.session_count)) {
        this.session_count = data().deepCopy(fields()[0].schema(), other.session_count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.total_count)) {
        this.total_count = data().deepCopy(fields()[1].schema(), other.total_count);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sum_of_squares)) {
        this.sum_of_squares = data().deepCopy(fields()[2].schema(), other.sum_of_squares);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mean)) {
        this.mean = data().deepCopy(fields()[3].schema(), other.mean);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.variance)) {
        this.variance = data().deepCopy(fields()[4].schema(), other.variance);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EventSubtypeStatisticsData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.session_count)) {
        this.session_count = data().deepCopy(fields()[0].schema(), other.session_count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.total_count)) {
        this.total_count = data().deepCopy(fields()[1].schema(), other.total_count);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sum_of_squares)) {
        this.sum_of_squares = data().deepCopy(fields()[2].schema(), other.sum_of_squares);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.mean)) {
        this.mean = data().deepCopy(fields()[3].schema(), other.mean);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.variance)) {
        this.variance = data().deepCopy(fields()[4].schema(), other.variance);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'session_count' field.
      * @return The value.
      */
    public java.lang.Long getSessionCount() {
      return session_count;
    }

    /**
      * Sets the value of the 'session_count' field.
      * @param value The value of 'session_count'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder setSessionCount(long value) {
      validate(fields()[0], value);
      this.session_count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'session_count' field has been set.
      * @return True if the 'session_count' field has been set, false otherwise.
      */
    public boolean hasSessionCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'session_count' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder clearSessionCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'total_count' field.
      * @return The value.
      */
    public java.lang.Long getTotalCount() {
      return total_count;
    }

    /**
      * Sets the value of the 'total_count' field.
      * @param value The value of 'total_count'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder setTotalCount(long value) {
      validate(fields()[1], value);
      this.total_count = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'total_count' field has been set.
      * @return True if the 'total_count' field has been set, false otherwise.
      */
    public boolean hasTotalCount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'total_count' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder clearTotalCount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'sum_of_squares' field.
      * @return The value.
      */
    public java.lang.Long getSumOfSquares() {
      return sum_of_squares;
    }

    /**
      * Sets the value of the 'sum_of_squares' field.
      * @param value The value of 'sum_of_squares'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder setSumOfSquares(long value) {
      validate(fields()[2], value);
      this.sum_of_squares = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'sum_of_squares' field has been set.
      * @return True if the 'sum_of_squares' field has been set, false otherwise.
      */
    public boolean hasSumOfSquares() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'sum_of_squares' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder clearSumOfSquares() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'mean' field.
      * @return The value.
      */
    public java.lang.Double getMean() {
      return mean;
    }

    /**
      * Sets the value of the 'mean' field.
      * @param value The value of 'mean'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder setMean(double value) {
      validate(fields()[3], value);
      this.mean = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'mean' field has been set.
      * @return True if the 'mean' field has been set, false otherwise.
      */
    public boolean hasMean() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'mean' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder clearMean() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'variance' field.
      * @return The value.
      */
    public java.lang.Double getVariance() {
      return variance;
    }

    /**
      * Sets the value of the 'variance' field.
      * @param value The value of 'variance'.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder setVariance(double value) {
      validate(fields()[4], value);
      this.variance = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'variance' field has been set.
      * @return True if the 'variance' field has been set, false otherwise.
      */
    public boolean hasVariance() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'variance' field.
      * @return This builder.
      */
    public com.refactorlabs.cs378.assign8.EventSubtypeStatisticsData.Builder clearVariance() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public EventSubtypeStatisticsData build() {
      try {
        EventSubtypeStatisticsData record = new EventSubtypeStatisticsData();
        record.session_count = fieldSetFlags()[0] ? this.session_count : (java.lang.Long) defaultValue(fields()[0]);
        record.total_count = fieldSetFlags()[1] ? this.total_count : (java.lang.Long) defaultValue(fields()[1]);
        record.sum_of_squares = fieldSetFlags()[2] ? this.sum_of_squares : (java.lang.Long) defaultValue(fields()[2]);
        record.mean = fieldSetFlags()[3] ? this.mean : (java.lang.Double) defaultValue(fields()[3]);
        record.variance = fieldSetFlags()[4] ? this.variance : (java.lang.Double) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
